Add refactor calculater component by function comp
girma336/math-magicians pull request #4
Opened 2022-12-14 18:05 UTC by girma336

### In this project I  refactor the Calculator component you developed in the past projects. Instead of using class based components, you will use now hooks.
 
- [ ]  Added calculetFun.js file to refactor previous project

2022-12-14 18:29 UTC, mckent05 requested changes
Hi @girma336, 

# STATUS: CHANGES REQUIRED ♻️ ♻️ 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/207265056-d056ea78-77c5-4b66-802e-694a5ed4ecf3.gif)

## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👍 👍 
- You used the right workflow for this milestone 👏 👏 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-14 18:29 UTC, mckent05 commented on src/components/CalculatorFun.js
> +export default CalculatorFun;
- Good job done so far, I noticed you have opened a new component instead of refactoring the `Calculator.js` component, according to the project requirements, you are to refactor the `Calculator.js` component. Please fix this 👍 👍. 
- Your `App.js` component should render the `Calculator.js` component 👍

2022-12-15 07:46 UTC, Abenezer-Tilahun commented on src/components/CalculatorFun.js
> +export default CalculatorFun;
Fixed.

2022-12-15 07:47 UTC, Abenezer-Tilahun approved these changes
Hi @girma336 
 
Your project is complete  👍 💯   There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 👏🏻

✔️ No linter errors.
✔️ You used correct Git-Flow.
✔️ Professional README  
✔️ Good Commit Messages
✔️ Refactor with hooks


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-15 18:27 UTC, merged